### PR TITLE
Issue 12 + announce presence changes

### PR DESCRIPTION
**Pull request by timjon**
Fixed issue #12 and removed the activePort field from the announce presence message

### CODE REVIEW

**Review by maansaake — CHANGES_REQUESTED** [review]
You can remove the demo IPs as well

**Comment by BigPapaKlonas** [comment]
Tested with Tim and nothing was broker. :thumbsup:

**Review by BigPapaKlonas — APPROVED** [review]

**Comment by kosara-g** [comment]
@maansthoernvik can you take another look and see if it's okay now?

**Review by maansaake — APPROVED** [review]
Looks good!

**Pull request merged**
